import type { SuggestedSong } from "./gemini-suggestions";

export const PRESET_SEED_DATA: Record<string, { category: string; subTheme: string; songs: SuggestedSong[] }> = {
  "trending-hits": {
    category: "Trending",
    subTheme: "Trending Hits",
    songs: [
      { title: "Espresso", artist: "Sabrina Carpenter", year: "2024" },
      { title: "Cruel Summer", artist: "Taylor Swift", year: "2019" },
      { title: "Flowers", artist: "Miley Cyrus", year: "2023" },
      { title: "As It Was", artist: "Harry Styles", year: "2022" },
      { title: "Good 4 U", artist: "Olivia Rodrigo", year: "2021" },
      { title: "Blinding Lights", artist: "The Weeknd", year: "2020" },
      { title: "Levitating", artist: "Dua Lipa", year: "2020" },
      { title: "Watermelon Sugar", artist: "Harry Styles", year: "2019" },
      { title: "Dance The Night", artist: "Dua Lipa", year: "2023" },
      { title: "Stay", artist: "The Kid LAROI & Justin Bieber", year: "2021" },
    ],
  },
  "male-icons": {
    category: "Male / Female / Duet",
    subTheme: "Males",
    songs: [
      { title: "Fly Me to the Moon", artist: "Frank Sinatra", year: "1964" },
      { title: "Superstition", artist: "Stevie Wonder", year: "1972" },
      { title: "Your Song", artist: "Elton John", year: "1970" },
      { title: "Billie Jean", artist: "Michael Jackson", year: "1982" },
      { title: "Piano Man", artist: "Billy Joel", year: "1973" },
      { title: "Bohemian Rhapsody", artist: "Queen", year: "1975" },
      { title: "Purple Rain", artist: "Prince", year: "1984" },
      { title: "Careless Whisper", artist: "George Michael", year: "1984" },
      { title: "Faith", artist: "George Michael", year: "1987" },
      { title: "Sweet Caroline", artist: "Neil Diamond", year: "1969" },
    ],
  },
  "divas": {
    category: "Male / Female / Duet",
    subTheme: "Divas",
    songs: [
      { title: "I Will Always Love You", artist: "Whitney Houston", year: "1992" },
      { title: "Rolling in the Deep", artist: "Adele", year: "2010" },
      { title: "My Heart Will Go On", artist: "Celine Dion", year: "1997" },
      { title: "Hero", artist: "Mariah Carey", year: "1993" },
      { title: "If I Were a Boy", artist: "Beyoncé", year: "2008" },
      { title: "Respect", artist: "Aretha Franklin", year: "1967" },
      { title: "Stronger (What Doesn't Kill You)", artist: "Kelly Clarkson", year: "2011" },
      { title: "Chandelier", artist: "Sia", year: "2014" },
      { title: "Because You Loved Me", artist: "Celine Dion", year: "1996" },
      { title: "Believe", artist: "Cher", year: "1998" },
    ],
  },
  "duets": {
    category: "Male / Female / Duet",
    subTheme: "Duets",
    songs: [
      { title: "Ain't No Mountain High Enough", artist: "Marvin Gaye & Tammi Terrell", year: "1967" },
      { title: "Shallow", artist: "Lady Gaga & Bradley Cooper", year: "2018" },
      { title: "Endless Love", artist: "Diana Ross & Lionel Richie", year: "1981" },
      { title: "Don't Go Breaking My Heart", artist: "Elton John & Kiki Dee", year: "1976" },
      { title: "Islands in the Stream", artist: "Kenny Rogers & Dolly Parton", year: "1983" },
      { title: "Promiscuous", artist: "Nelly Furtado & Timbaland", year: "2006" },
      { title: "Up Where We Belong", artist: "Joe Cocker & Jennifer Warnes", year: "1982" },
      { title: "Under Pressure", artist: "Queen & David Bowie", year: "1981" },
      { title: "A Whole New World", artist: "Peabo Bryson & Regina Belle", year: "1992" },
      { title: "Empire State of Mind", artist: "JAY-Z & Alicia Keys", year: "2009" },
    ],
  },
  "christmas": {
    category: "Holidays",
    subTheme: "Christmas",
    songs: [
      { title: "All I Want for Christmas Is You", artist: "Mariah Carey", year: "1994" },
      { title: "Last Christmas", artist: "Wham!", year: "1984" },
      { title: "Rockin' Around the Christmas Tree", artist: "Brenda Lee", year: "1958" },
      { title: "Jingle Bell Rock", artist: "Bobby Helms", year: "1957" },
      { title: "Feliz Navidad", artist: "José Feliciano", year: "1970" },
      { title: "Wonderful Christmastime", artist: "Paul McCartney", year: "1979" },
      { title: "Santa Tell Me", artist: "Ariana Grande", year: "2014" },
      { title: "Underneath the Tree", artist: "Kelly Clarkson", year: "2013" },
      { title: "Let It Snow! Let It Snow! Let It Snow!", artist: "Dean Martin", year: "1959" },
      { title: "White Christmas", artist: "Bing Crosby", year: "1942" },
    ],
  },
  "halloween": {
    category: "Holidays",
    subTheme: "Halloween",
    songs: [
      { title: "Thriller", artist: "Michael Jackson", year: "1982" },
      { title: "Ghostbusters", artist: "Ray Parker Jr.", year: "1984" },
      { title: "Monster Mash", artist: "Bobby Pickett", year: "1962" },
      { title: "Somebody's Watching Me", artist: "Rockwell", year: "1984" },
      { title: "Superstition", artist: "Stevie Wonder", year: "1972" },
      { title: "Highway to Hell", artist: "AC/DC", year: "1979" },
      { title: "Sweet Dreams (Are Made of This)", artist: "Eurythmics", year: "1983" },
      { title: "Disturbia", artist: "Rihanna", year: "2008" },
      { title: "Bury a Friend", artist: "Billie Eilish", year: "2019" },
      { title: "Time Warp", artist: "Little Nell, Patricia Quinn & Richard O'Brien", year: "1975" },
    ],
  },
  "70s": {
    category: "Decades",
    subTheme: "70's",
    songs: [
      { title: "Stayin' Alive", artist: "Bee Gees", year: "1977" },
      { title: "Dancing Queen", artist: "ABBA", year: "1976" },
      { title: "September", artist: "Earth, Wind & Fire", year: "1978" },
      { title: "Hotel California", artist: "Eagles", year: "1976" },
      { title: "Bohemian Rhapsody", artist: "Queen", year: "1975" },
      { title: "I Will Survive", artist: "Gloria Gaynor", year: "1978" },
      { title: "Y.M.C.A.", artist: "Village People", year: "1978" },
      { title: "Dreams", artist: "Fleetwood Mac", year: "1977" },
      { title: "Don't Stop 'Til You Get Enough", artist: "Michael Jackson", year: "1979" },
      { title: "Le Freak", artist: "Chic", year: "1978" },
    ],
  },
  "80s": {
    category: "Decades",
    subTheme: "80's",
    songs: [
      { title: "Don't Stop Believin'", artist: "Journey", year: "1981" },
      { title: "Livin' on a Prayer", artist: "Bon Jovi", year: "1986" },
      { title: "Take On Me", artist: "a-ha", year: "1985" },
      { title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", year: "1983" },
      { title: "I Wanna Dance with Somebody", artist: "Whitney Houston", year: "1987" },
      { title: "Sweet Dreams (Are Made of This)", artist: "Eurythmics", year: "1983" },
      { title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: "1987" },
      { title: "Africa", artist: "Toto", year: "1982" },
      { title: "Total Eclipse of the Heart", artist: "Bonnie Tyler", year: "1983" },
      { title: "Never Gonna Give You Up", artist: "Rick Astley", year: "1987" },
    ],
  },
  "90s": {
    category: "Decades",
    subTheme: "90's",
    songs: [
      { title: "I Want It That Way", artist: "Backstreet Boys", year: "1999" },
      { title: "Wannabe", artist: "Spice Girls", year: "1996" },
      { title: "No Scrubs", artist: "TLC", year: "1999" },
      { title: "...Baby One More Time", artist: "Britney Spears", year: "1998" },
      { title: "Wonderwall", artist: "Oasis", year: "1995" },
      { title: "Torn", artist: "Natalie Imbruglia", year: "1997" },
      { title: "Say My Name", artist: "Destiny's Child", year: "1999" },
      { title: "Man! I Feel Like a Woman!", artist: "Shania Twain", year: "1997" },
      { title: "Smells Like Teen Spirit", artist: "Nirvana", year: "1991" },
      { title: "Waterfalls", artist: "TLC", year: "1994" },
    ],
  },
  "00s": {
    category: "Decades",
    subTheme: "00's",
    songs: [
      { title: "Since U Been Gone", artist: "Kelly Clarkson", year: "2004" },
      { title: "Mr. Brightside", artist: "The Killers", year: "2004" },
      { title: "Toxic", artist: "Britney Spears", year: "2003" },
      { title: "Hey Ya!", artist: "Outkast", year: "2003" },
      { title: "Crazy in Love", artist: "Beyoncé feat. JAY-Z", year: "2003" },
      { title: "I Gotta Feeling", artist: "Black Eyed Peas", year: "2009" },
      { title: "Umbrella", artist: "Rihanna feat. JAY-Z", year: "2007" },
      { title: "Complicated", artist: "Avril Lavigne", year: "2002" },
      { title: "Sugar, We're Goin Down", artist: "Fall Out Boy", year: "2005" },
      { title: "Bleeding Love", artist: "Leona Lewis", year: "2007" },
    ],
  },
  "10s": {
    category: "Decades",
    subTheme: "10's",
    songs: [
      { title: "Rolling in the Deep", artist: "Adele", year: "2010" },
      { title: "Uptown Funk", artist: "Mark Ronson feat. Bruno Mars", year: "2014" },
      { title: "Shake It Off", artist: "Taylor Swift", year: "2014" },
      { title: "Shape of You", artist: "Ed Sheeran", year: "2017" },
      { title: "Call Me Maybe", artist: "Carly Rae Jepsen", year: "2011" },
      { title: "Roar", artist: "Katy Perry", year: "2013" },
      { title: "Can't Stop the Feeling!", artist: "Justin Timberlake", year: "2016" },
      { title: "Happy", artist: "Pharrell Williams", year: "2013" },
      { title: "Shut Up and Dance", artist: "WALK THE MOON", year: "2014" },
      { title: "Counting Stars", artist: "OneRepublic", year: "2013" },
    ],
  },
  "hard-rock": {
    category: "Rock",
    subTheme: "Hard Rock",
    songs: [
      { title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: "1987" },
      { title: "Back in Black", artist: "AC/DC", year: "1980" },
      { title: "Pour Some Sugar on Me", artist: "Def Leppard", year: "1987" },
      { title: "You Give Love a Bad Name", artist: "Bon Jovi", year: "1986" },
      { title: "Welcome to the Jungle", artist: "Guns N' Roses", year: "1987" },
      { title: "Here I Go Again", artist: "Whitesnake", year: "1982" },
      { title: "Jump", artist: "Van Halen", year: "1984" },
      { title: "Crazy Train", artist: "Ozzy Osbourne", year: "1980" },
      { title: "Kickstart My Heart", artist: "Mötley Crüe", year: "1989" },
      { title: "We're Not Gonna Take It", artist: "Twisted Sister", year: "1984" },
    ],
  },
  "alternative": {
    category: "Rock",
    subTheme: "Alternative",
    songs: [
      { title: "Creep", artist: "Radiohead", year: "1992" },
      { title: "Zombie", artist: "The Cranberries", year: "1994" },
      { title: "Seven Nation Army", artist: "The White Stripes", year: "2003" },
      { title: "Buddy Holly", artist: "Weezer", year: "1994" },
      { title: "Losing My Religion", artist: "R.E.M.", year: "1991" },
      { title: "Basket Case", artist: "Green Day", year: "1994" },
      { title: "Use Somebody", artist: "Kings of Leon", year: "2008" },
      { title: "Song 2", artist: "Blur", year: "1997" },
      { title: "Sex on Fire", artist: "Kings of Leon", year: "2008" },
      { title: "1979", artist: "The Smashing Pumpkins", year: "1995" },
    ],
  },
  "metal": {
    category: "Rock",
    subTheme: "Metal",
    songs: [
      { title: "Enter Sandman", artist: "Metallica", year: "1991" },
      { title: "Paranoid", artist: "Black Sabbath", year: "1970" },
      { title: "The Trooper", artist: "Iron Maiden", year: "1983" },
      { title: "Chop Suey!", artist: "System of a Down", year: "2001" },
      { title: "Holy Diver", artist: "Dio", year: "1983" },
      { title: "Breaking the Law", artist: "Judas Priest", year: "1980" },
      { title: "Master of Puppets", artist: "Metallica", year: "1986" },
      { title: "Down with the Sickness", artist: "Disturbed", year: "2000" },
      { title: "Numb", artist: "Linkin Park", year: "2003" },
      { title: "Du Hast", artist: "Rammstein", year: "1997" },
    ],
  },
  "hiphop-groups": {
    category: "Hip-Hop",
    subTheme: "Groups",
    songs: [
      { title: "Rapper's Delight", artist: "The Sugarhill Gang", year: "1979" },
      { title: "Walk This Way", artist: "Run-D.M.C. feat. Aerosmith", year: "1986" },
      { title: "C.R.E.A.M.", artist: "Wu-Tang Clan", year: "1993" },
      { title: "Hip Hop Hooray", artist: "Naughty by Nature", year: "1993" },
      { title: "Intergalactic", artist: "Beastie Boys", year: "1998" },
      { title: "Ms. Jackson", artist: "Outkast", year: "2000" },
      { title: "Push It", artist: "Salt-N-Pepa", year: "1986" },
      { title: "Fight For Your Right", artist: "Beastie Boys", year: "1986" },
      { title: "Regulate", artist: "Warren G & Nate Dogg", year: "1994" },
      { title: "Where the Party At", artist: "Jagged Edge feat. Nelly", year: "2001" },
    ],
  },
  "b-boys": {
    category: "Hip-Hop",
    subTheme: "B-Boys",
    songs: [
      { title: "It Takes Two", artist: "Rob Base & DJ E-Z Rock", year: "1988" },
      { title: "The Message", artist: "Grandmaster Flash and the Furious Five", year: "1982" },
      { title: "Paid in Full", artist: "Eric B. & Rakim", year: "1987" },
      { title: "Bust a Move", artist: "Young MC", year: "1989" },
      { title: "O.P.P.", artist: "Naughty by Nature", year: "1991" },
      { title: "Jump Around", artist: "House of Pain", year: "1992" },
      { title: "Humpty Dance", artist: "Digital Underground", year: "1990" },
      { title: "U Can't Touch This", artist: "MC Hammer", year: "1990" },
      { title: "Ice Ice Baby", artist: "Vanilla Ice", year: "1990" },
      { title: "Parents Just Don't Understand", artist: "DJ Jazzy Jeff & The Fresh Prince", year: "1988" },
    ],
  },
  "ladies-hiphop": {
    category: "Hip-Hop",
    subTheme: "Ladies",
    songs: [
      { title: "Doo Wop (That Thing)", artist: "Lauryn Hill", year: "1998" },
      { title: "Work It", artist: "Missy Elliott", year: "2002" },
      { title: "Super Bass", artist: "Nicki Minaj", year: "2010" },
      { title: "Let Me Blow Ya Mind", artist: "Eve feat. Gwen Stefani", year: "2001" },
      { title: "Shoop", artist: "Salt-N-Pepa", year: "1993" },
      { title: "Get Ur Freak On", artist: "Missy Elliott", year: "2001" },
      { title: "Starships", artist: "Nicki Minaj", year: "2012" },
      { title: "U.N.I.T.Y.", artist: "Queen Latifah", year: "1993" },
      { title: "Whatta Man", artist: "Salt-N-Pepa with En Vogue", year: "1993" },
      { title: "Bodak Yellow", artist: "Cardi B", year: "2017" },
    ],
  },
  "disney": {
    category: "Movies & Theater",
    subTheme: "Disney",
    songs: [
      { title: "A Whole New World", artist: "Brad Kane & Lea Salonga", year: "1992" },
      { title: "Let It Go", artist: "Idina Menzel", year: "2013" },
      { title: "Under the Sea", artist: "Samuel E. Wright", year: "1989" },
      { title: "Beauty and the Beast", artist: "Angela Lansbury", year: "1991" },
      { title: "How Far I'll Go", artist: "Auli'i Cravalho", year: "2016" },
      { title: "You're Welcome", artist: "Dwayne Johnson", year: "2016" },
      { title: "Part of Your World", artist: "Jodi Benson", year: "1989" },
      { title: "Hakuna Matata", artist: "Nathan Lane & Ernie Sabella", year: "1994" },
      { title: "Colors of the Wind", artist: "Judy Kuhn", year: "1995" },
      { title: "Can You Feel the Love Tonight", artist: "Elton John", year: "1994" },
    ],
  },
  "movies": {
    category: "Movies & Theater",
    subTheme: "Movies",
    songs: [
      { title: "Eye of the Tiger", artist: "Survivor", year: "1982" },
      { title: "My Heart Will Go On", artist: "Celine Dion", year: "1997" },
      { title: "(I've Had) The Time of My Life", artist: "Bill Medley & Jennifer Warnes", year: "1987" },
      { title: "Stayin' Alive", artist: "Bee Gees", year: "1977" },
      { title: "Footloose", artist: "Kenny Loggins", year: "1984" },
      { title: "Ghostbusters", artist: "Ray Parker Jr.", year: "1984" },
      { title: "Danger Zone", artist: "Kenny Loggins", year: "1986" },
      { title: "Men in Black", artist: "Will Smith", year: "1997" },
      { title: "I Will Always Love You", artist: "Whitney Houston", year: "1992" },
      { title: "Shallow", artist: "Lady Gaga & Bradley Cooper", year: "2018" },
    ],
  },
  "broadway": {
    category: "Movies & Theater",
    subTheme: "Broadway",
    songs: [
      { title: "Defying Gravity", artist: "Idina Menzel & Kristin Chenoweth", year: "2003" },
      { title: "Don't Rain on My Parade", artist: "Barbra Streisand", year: "1964" },
      { title: "Memory", artist: "Elaine Paige", year: "1981" },
      { title: "You'll Be Back", artist: "Jonathan Groff", year: "2015" },
      { title: "All That Jazz", artist: "Chita Rivera", year: "1975" },
      { title: "The Phantom of the Opera", artist: "Sarah Brightman & Michael Crawford", year: "1986" },
      { title: "Cabaret", artist: "Liza Minnelli", year: "1972" },
      { title: "Seasons of Love", artist: "Cast of Rent", year: "1996" },
      { title: "I Dreamed a Dream", artist: "Patti LuPone", year: "1985" },
      { title: "Alexander Hamilton", artist: "Lin-Manuel Miranda", year: "2015" },
    ],
  },
  "kpop": {
    category: "International",
    subTheme: "K-Pop",
    songs: [
      { title: "Gangnam Style", artist: "PSY", year: "2012" },
      { title: "Dynamite", artist: "BTS", year: "2020" },
      { title: "DDU-DU DDU-DU", artist: "BLACKPINK", year: "2018" },
      { title: "Butter", artist: "BTS", year: "2021" },
      { title: "Kill This Love", artist: "BLACKPINK", year: "2019" },
      { title: "Cupid", artist: "FIFTY FIFTY", year: "2023" },
      { title: "TT", artist: "TWICE", year: "2016" },
      { title: "Fantastic Baby", artist: "BIGBANG", year: "2012" },
      { title: "Love Scenario", artist: "iKON", year: "2018" },
      { title: "Super Shy", artist: "NewJeans", year: "2023" },
    ],
  },
  "jpop": {
    category: "International",
    subTheme: "J-Pop",
    songs: [
      { title: "A Cruel Angel's Thesis", artist: "Yoko Takahashi", year: "1995" },
      { title: "First Love", artist: "Hikaru Utada", year: "1999" },
      { title: "Stay With Me", artist: "Miki Matsubara", year: "1979" },
      { title: "Plastic Love", artist: "Mariya Takeuchi", year: "1984" },
      { title: "Lemon", artist: "Kenshi Yonezu", year: "2018" },
      { title: "Idol", artist: "YOASOBI", year: "2023" },
      { title: "Gurenge", artist: "LiSA", year: "2019" },
      { title: "Heavy Rotation", artist: "AKB48", year: "2010" },
      { title: "Blue Bird", artist: "Ikimonogakari", year: "2008" },
      { title: "Silhouette", artist: "KANA-BOON", year: "2014" },
    ],
  },
  "reggaeton": {
    category: "International",
    subTheme: "Reggaeton",
    songs: [
      { title: "Despacito", artist: "Luis Fonsi feat. Daddy Yankee", year: "2017" },
      { title: "Gasolina", artist: "Daddy Yankee", year: "2004" },
      { title: "Dákiti", artist: "Bad Bunny & Jhay Cortez", year: "2020" },
      { title: "Mi Gente", artist: "J Balvin & Willy William", year: "2017" },
      { title: "Bailando", artist: "Enrique Iglesias", year: "2014" },
      { title: "Danza Kuduro", artist: "Don Omar feat. Lucenzo", year: "2010" },
      { title: "Hips Don't Lie", artist: "Shakira feat. Wyclef Jean", year: "2006" },
      { title: "Pepas", artist: "Farruko", year: "2021" },
      { title: "Con Calma", artist: "Daddy Yankee & Snow", year: "2019" },
      { title: "Titi Me Preguntó", artist: "Bad Bunny", year: "2022" },
    ],
  },
  "caribbean": {
    category: "International",
    subTheme: "Caribbean",
    songs: [
      { title: "Three Little Birds", artist: "Bob Marley & The Wailers", year: "1977" },
      { title: "Could You Be Loved", artist: "Bob Marley & The Wailers", year: "1980" },
      { title: "Is This Love", artist: "Bob Marley & The Wailers", year: "1978" },
      { title: "One Love / People Get Ready", artist: "Bob Marley & The Wailers", year: "1977" },
      { title: "It Wasn't Me", artist: "Shaggy feat. RikRok", year: "2000" },
      { title: "No Letting Go", artist: "Wayne Wonder", year: "2002" },
      { title: "Temperature", artist: "Sean Paul", year: "2005" },
      { title: "Get Busy", artist: "Sean Paul", year: "2002" },
      { title: "Red Red Wine", artist: "UB40", year: "1983" },
      { title: "Sweat (A La La La La Long)", artist: "Inner Circle", year: "1992" },
    ],
  },
};
